// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using web.api.DataAccess;

namespace web.api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    internal class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("TeamUser", b =>
            {
                b.Property<int>("MembersId")
                    .HasColumnType("INTEGER");

                b.Property<int>("TeamsId")
                    .HasColumnType("INTEGER");

                b.HasKey("MembersId", "TeamsId");

                b.HasIndex("TeamsId");

                b.ToTable("TeamUser");
            });

            modelBuilder.Entity("web.api.App.Recipes.Recipe", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Description")
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("Recipes");
            });

            modelBuilder.Entity("web.api.App.Teams.Team", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Name")
                    .HasColumnType("TEXT");

                b.Property<int>("OwnerUserId")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("OwnerUserId");

                b.ToTable("Teams");
            });

            modelBuilder.Entity("web.api.App.Users.User", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int?>("ActiveTeamId")
                    .HasColumnType("INTEGER");

                b.Property<string>("Email")
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .HasColumnType("TEXT");

                b.Property<int>("Role")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.ToTable("Users");
            });

            modelBuilder.Entity("TeamUser", b =>
            {
                b.HasOne("web.api.App.Users.User", null)
                    .WithMany()
                    .HasForeignKey("MembersId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("web.api.App.Teams.Team", null)
                    .WithMany()
                    .HasForeignKey("TeamsId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("web.api.App.Teams.Team", b =>
            {
                b.HasOne("web.api.App.Users.User", "Owner")
                    .WithMany()
                    .HasForeignKey("OwnerUserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Owner");
            });
#pragma warning restore 612, 618
        }
    }
}